In [5]:
import sun1

In [1]:
import numpy as np

In [8]:
a = np.arange(36).reshape(6,6)

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
from skimage.util import view_as_blocks

In [17]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [20]:
b = view_as_blocks(a,(3,3))

In [54]:
b.shape

(2, 2, 3, 3)

In [55]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [27]:
b[0,0,]

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]])

In [49]:
c.shape

(2, 2, 9)

In [51]:
c

array([[[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]],

       [[18, 19, 20, 24, 25, 26, 30, 31, 32],
        [21, 22, 23, 27, 28, 29, 33, 34, 35]]])

In [52]:
c

array([[[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]],

       [[18, 19, 20, 24, 25, 26, 30, 31, 32],
        [21, 22, 23, 27, 28, 29, 33, 34, 35]]])

In [41]:
np.max(c,axis=2)

array([[14, 17],
       [32, 35]])

In [42]:
from skimage.util import view_as_blocks,view_as_windows

In [43]:
b = view_as_windows(a,3,3)

In [44]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [45]:
import inspect

In [47]:
print(inspect.getsource(view_as_blocks))

def view_as_blocks(arr_in, block_shape):
    """Block view of the input n-dimensional array (using re-striding).

    Blocks are non-overlapping views of the input array.

    Parameters
    ----------
    arr_in : ndarray
        N-d input array.
    block_shape : tuple
        The shape of the block. Each dimension must divide evenly into the
        corresponding dimensions of `arr_in`.

    Returns
    -------
    arr_out : ndarray
        Block view of the input array.  If `arr_in` is non-contiguous, a copy
        is made.

    Examples
    --------
    >>> import numpy as np
    >>> from skimage.util.shape import view_as_blocks
    >>> A = np.arange(4*4).reshape(4,4)
    >>> A
    array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11],
           [12, 13, 14, 15]])
    >>> B = view_as_blocks(A, block_shape=(2, 2))
    >>> B[0, 0]
    array([[0, 1],
           [4, 5]])
    >>> B[0, 1]
    array([[2, 3],
           [6, 7]])
    >>> B[1, 0, 1, 1]
    13



In [58]:
A = np.eye(10)
# 행열의 값을 하나로 표현해라 / ->뒤에 있는게 결과값
diag = np.einsum("ii->i",A)
# 핼열의 값을 더해라
trace = np.einsum("ii->",A)

print(diag)
print(trace)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10.0


In [59]:
A

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
a = np.arange(6).reshape(2,3)

In [64]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
# 행열을 전치해라
np.einsum("ij->ji",a)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [67]:
# ij있는값을 합쳐라
np.einsum("ij->",a)

15

In [68]:
np.einsum("ij->j",a)

array([3, 5, 7])

In [69]:
np.sum(a,axis=0)

array([3, 5, 7])

In [73]:
b = np.arange(3)
np.einsum("ik,k->i",a,b)

array([ 5, 14])

In [75]:
b

array([0, 1, 2])

In [81]:
a = np.arange(3)
b = np.arange(3,6)

In [ ]:
# 외적
a = np.arange(3)
b = np.arange(3,7)


In [87]:
np.repeat([[3,4],[5,6]],3,axis=1)

array([[3, 3, 3, 4, 4, 4],
       [5, 5, 5, 6, 6, 6]])

In [94]:
a = np.arange(3)
b = np.arange(3,6)

In [96]:
a

array([0, 1, 2])

In [97]:
b

array([3, 4, 5])

In [92]:
x =np.convolve(a,b)

In [93]:
x

array([ 0,  3, 10, 13, 10])

In [98]:
from scipy.signal import convolve

In [100]:
a = np.array([1,2,3,4], dtype="f4")

In [104]:
# 뮤터블 특징으로 타입을 변경하려면 재할당 해야한다.
a = a.astype("uint")

In [105]:
a

array([1, 2, 3, 4], dtype=uint32)

In [ ]:
# vectorize는 벡터라이즈가 지원되지 않는 함수를 벡터라이즈화 해서 처리 해준다.
# high-order 함수
# 데코레이터로 사용 할 수 있다,
# @np.vectorize
# 벡터라이즈는 비트맵 이미지를 벡터화 시키는 것이다.
a = np.vectorize()