In [5]:
import sun1

In [1]:
import numpy as np
# np의 window 개념알기

In [8]:
a = np.arange(36).reshape(6,6)

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
from skimage.util import view_as_blocks

In [17]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [20]:
b = view_as_blocks(a,(3,3))

In [54]:
b.shape

(2, 2, 3, 3)

In [55]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [27]:
b[0,0,]

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]])

In [49]:
c.shape

(2, 2, 9)

In [51]:
c

array([[[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]],

       [[18, 19, 20, 24, 25, 26, 30, 31, 32],
        [21, 22, 23, 27, 28, 29, 33, 34, 35]]])

In [52]:
c

array([[[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]],

       [[18, 19, 20, 24, 25, 26, 30, 31, 32],
        [21, 22, 23, 27, 28, 29, 33, 34, 35]]])

In [41]:
np.max(c,axis=2)

array([[14, 17],
       [32, 35]])

In [42]:
from skimage.util import view_as_blocks,view_as_windows

In [43]:
b = view_as_windows(a,3,3)

In [44]:
b

array([[[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14]],

        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [24, 25, 26],
         [30, 31, 32]],

        [[21, 22, 23],
         [27, 28, 29],
         [33, 34, 35]]]])

In [45]:
import inspect

In [47]:
print(inspect.getsource(view_as_blocks))

def view_as_blocks(arr_in, block_shape):
    """Block view of the input n-dimensional array (using re-striding).

    Blocks are non-overlapping views of the input array.

    Parameters
    ----------
    arr_in : ndarray
        N-d input array.
    block_shape : tuple
        The shape of the block. Each dimension must divide evenly into the
        corresponding dimensions of `arr_in`.

    Returns
    -------
    arr_out : ndarray
        Block view of the input array.  If `arr_in` is non-contiguous, a copy
        is made.

    Examples
    --------
    >>> import numpy as np
    >>> from skimage.util.shape import view_as_blocks
    >>> A = np.arange(4*4).reshape(4,4)
    >>> A
    array([[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11],
           [12, 13, 14, 15]])
    >>> B = view_as_blocks(A, block_shape=(2, 2))
    >>> B[0, 0]
    array([[0, 1],
           [4, 5]])
    >>> B[0, 1]
    array([[2, 3],
           [6, 7]])
    >>> B[1, 0, 1, 1]
    13

